### ISSUE TITLE
I have successfully made E5 a non-battery desktop audio interface 

### ISSUE THREAD

**Issue by pbjacob** [Jamesits/sound-blaster-e5-battery#1]
In order to simulate a battery to cheat the mainboard, it's necessary to find some 5V power on it. 
Luckily, the pins of the USB-HOST can be easily obtained on the back of the mainboard, which are power+, data+, data-, power-. 
Actually, when using E5 as a desktop audio card, we don't need USB-HOST port at all, so this port can be used as external power. 
The details can be found at : https://zhuanlan.zhihu.com/p/90036682
Sorry for writing the article in Chinese, but anyway, I posted lots of photos, so I think it's not hard to get the whole idea and procedure.

**Comment by Jamesits** [comment]
I've included the information you provided into the repo. Thank you!

**Comment by adi-works** [comment]
This is the best solution, now that I've given up on a battery replacement solution. The original battery sucks anyway. You get can a 10000mAh Xiaomi power bank and use the bands that come with the E5 to bind them together. That would make a much better mobile DAC/AMP setup. With that said, can you use a phone charger to power it up? I don't really care for connecting to a laptop or PC, because you change its settings from the app, once it's paired.

As a note, I'll add that I turned to Creative recently in attempt to see if they'd go out of their way to fix my brick. After three emails with automated questions, I was given a boilerplate response that they regret to inform me my device is over a year (bought it in 2015 and it happened two years later so I was SOL already) and that the least they could offer me was a laughable 10% discount.

I will repurpose it as a proper desktop DAC/AMP, despite having invested in a serious desktop setup already and use its optical line out to feed my main DAC with Bluetooth and NFC.

PS, Google Translate does a great job in this case.

**Comment by anwenzen** [comment]
well done bro, this is I need. thank you so much

**Comment by burrowcat** [comment]
I implemented the method just recently and it worked fine being connected to PC + headphones. One suggestion regarding +5V point - it is safer not to solder to the resistor - there is a control point on the same trace nearby.

But the main purpose of this post is to describe one issue with the method.
It works differently whether E5's line out is connected to power amp or not.
If E5 boots connected, there will be no sound, although digital part works as usual -  USB device is recognized on the host, bluetooth is connectable, android app is operable. **NO SOUND !**
If E5 is fully booted before it gets connected to the amp - it sounds ok. But further manipulations with the line - disconnect/connect - revel a significant DC offset in the line, you will hear it thru the speakers at the moment of connecting/disconnecting.

I ended up with a new battery installed, the first I found in a local store which dimensionally suits - Li-Po 3.7V 1800mAh, two wire, so the trick with 10K resistor is anyway required.

@Jamesits
